// @generated by protoc-gen-es v1.3.1 with parameter "target=ts"
// @generated from file ibc/applications/transfer/v1/genesis.proto (package ibc.applications.transfer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type {
  BinaryReadOptions,
  FieldList,
  JsonReadOptions,
  JsonValue,
  PartialMessage,
  PlainMessage,
} from '@bufbuild/protobuf';
import { Message, proto3 } from '@bufbuild/protobuf';
import { DenomTrace, Params } from './transfer_pb';
import { Coin } from '../../../../cosmos/base/v1beta1/coin_pb';

/**
 * GenesisState defines the ibc-transfer genesis state
 *
 * @generated from message ibc.applications.transfer.v1.GenesisState
 */
export class GenesisState extends Message<GenesisState> {
  /**
   * @generated from field: string port_id = 1;
   */
  portId = '';

  /**
   * @generated from field: repeated ibc.applications.transfer.v1.DenomTrace denom_traces = 2;
   */
  denomTraces: DenomTrace[] = [];

  /**
   * @generated from field: ibc.applications.transfer.v1.Params params = 3;
   */
  params?: Params;

  /**
   * total_escrowed contains the total amount of tokens escrowed
   * by the transfer module
   *
   * @generated from field: repeated cosmos.base.v1beta1.Coin total_escrowed = 4;
   */
  totalEscrowed: Coin[] = [];

  constructor(data?: PartialMessage<GenesisState>) {
    super();
    proto3.util.initPartial(data, this);
  }

  static readonly runtime: typeof proto3 = proto3;
  static readonly typeName = 'ibc.applications.transfer.v1.GenesisState';
  static readonly fields: FieldList = proto3.util.newFieldList(() => [
    { no: 1, name: 'port_id', kind: 'scalar', T: 9 /* ScalarType.STRING */ },
    {
      no: 2,
      name: 'denom_traces',
      kind: 'message',
      T: DenomTrace,
      repeated: true,
    },
    { no: 3, name: 'params', kind: 'message', T: Params },
    { no: 4, name: 'total_escrowed', kind: 'message', T: Coin, repeated: true },
  ]);

  static fromBinary(
    bytes: Uint8Array,
    options?: Partial<BinaryReadOptions>,
  ): GenesisState {
    return new GenesisState().fromBinary(bytes, options);
  }

  static fromJson(
    jsonValue: JsonValue,
    options?: Partial<JsonReadOptions>,
  ): GenesisState {
    return new GenesisState().fromJson(jsonValue, options);
  }

  static fromJsonString(
    jsonString: string,
    options?: Partial<JsonReadOptions>,
  ): GenesisState {
    return new GenesisState().fromJsonString(jsonString, options);
  }

  static equals(
    a: GenesisState | PlainMessage<GenesisState> | undefined,
    b: GenesisState | PlainMessage<GenesisState> | undefined,
  ): boolean {
    return proto3.util.equals(GenesisState, a, b);
  }
}
