// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file ibc/applications/transfer/v1/tx.proto (package ibc.applications.transfer.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  MsgTransfer,
  MsgTransferResponse,
  MsgUpdateParams,
  MsgUpdateParamsResponse,
} from './tx_pb';
import { MethodKind } from '@bufbuild/protobuf';

/**
 * Msg defines the ibc/transfer Msg service.
 *
 * @generated from service ibc.applications.transfer.v1.Msg
 */
export const Msg = {
  typeName: 'ibc.applications.transfer.v1.Msg',
  methods: {
    /**
     * Transfer defines a rpc handler method for MsgTransfer.
     *
     * @generated from rpc ibc.applications.transfer.v1.Msg.Transfer
     */
    transfer: {
      name: 'Transfer',
      I: MsgTransfer,
      O: MsgTransferResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateParams defines a rpc handler for MsgUpdateParams.
     *
     * @generated from rpc ibc.applications.transfer.v1.Msg.UpdateParams
     */
    updateParams: {
      name: 'UpdateParams',
      I: MsgUpdateParams,
      O: MsgUpdateParamsResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
