// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file haqq/liquidvesting/v1/tx.proto (package haqq.liquidvesting.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgLiquidate, MsgLiquidateResponse, MsgRedeem, MsgRedeemResponse } from "./tx_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Msg defines the Msg service.
 *
 * @generated from service haqq.liquidvesting.v1.Msg
 */
export const Msg = {
  typeName: "haqq.liquidvesting.v1.Msg",
  methods: {
    /**
     * Liquidate transforms specified amount of tokens locked on vesting account into a new liquid token
     *
     * @generated from rpc haqq.liquidvesting.v1.Msg.Liquidate
     */
    liquidate: {
      name: "Liquidate",
      I: MsgLiquidate,
      O: MsgLiquidateResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Redeem burns liquid token and deposits corresponding amount of vesting token to the specified account
     *
     * @generated from rpc haqq.liquidvesting.v1.Msg.Redeem
     */
    redeem: {
      name: "Redeem",
      I: MsgRedeem,
      O: MsgRedeemResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

