codecov:
  branch: dev
  notify:
    after_n_builds: 2
    wait_for_ci: true

coverage:
  range: [70, 90]
  round: down
  precision: 2
  status:
    patch: false
    project: false

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1
      - type: patch
        target: 50

comment:
  layout: 'reach, diff, flags, files'
  behavior: default
  require_changes: true

parsers:
  javascript:
    enable_partials: yes

github_checks:
  annotations: true
