codecov:
  branch: dev

coverage:
  range: 70..90
  round: down
  precision: 2
  status:
    patch:
      enabled: false
    project:
      enabled: false

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: 70..90
      - type: patch

comment:
  layout:
    - reach
    - diff
    - flags
    - files
  behavior: default

parsers:
  javascript:
    enable_partials: yes

github_checks:
  annotations: true
