codecov:
  branch: dev
  require_ci_to_pass: true
  notify:
    after_n_builds: 2
    wait_for_ci: true

coverage:
  range: 60..80
  round: down
  precision: 2

flag_management:
  default_rules:
    carryforward: true
    statuses:
      - type: project
        target: auto
        threshold: 1
      - type: patch
        target: 50

comment:
  layout: 'reach, diff, flags, files'
  behavior: default

parsers:
  javascript:
    enable_partials: yes

github_checks:
  annotations: true
