cacheFolder: .yarn/cache

defaultSemverRangePrefix: ""

nodeLinker: node-modules

npmScopes:
  buf:
    npmRegistryServer: "https://buf.build/gen/npm/v1"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.6.0.cjs
