cacheFolder: .yarn/cache

changesetBaseRefs:
  - dev
  - origin/dev
  - upstream/dev

compressionLevel: mixed

defaultSemverRangePrefix: ""

enableGlobalCache: false

nodeLinker: node-modules

npmScopes:
  buf:
    npmRegistryServer: "https://buf.build/gen/npm/v1"

tsEnableAutoTypes: true

yarnPath: .yarn/releases/yarn-4.1.0.cjs
