cacheFolder: ".yarn/cache"
compressionLevel: "mixed"
defaultSemverRangePrefix: ""
nodeLinker: "node-modules"
tsEnableAutoTypes: true
enableGlobalCache: false
changesetBaseRefs:
  - "dev"
  - "origin/dev"
  - "upstream/dev"
npmScopes:
  buf:
    npmRegistryServer: "https://buf.build/gen/npm/v1"
yarnPath: .yarn/releases/yarn-4.0.1.cjs
