// Since: cosmos-sdk 0.43

// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file cosmos/base/reflection/v2alpha1/reflection.proto (package cosmos.base.reflection.v2alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  GetAuthnDescriptorRequest,
  GetAuthnDescriptorResponse,
  GetChainDescriptorRequest,
  GetChainDescriptorResponse,
  GetCodecDescriptorRequest,
  GetCodecDescriptorResponse,
  GetConfigurationDescriptorRequest,
  GetConfigurationDescriptorResponse,
  GetQueryServicesDescriptorRequest,
  GetQueryServicesDescriptorResponse,
  GetTxDescriptorRequest,
  GetTxDescriptorResponse,
} from './reflection_pb';
import { MethodKind } from '@bufbuild/protobuf';

/**
 * ReflectionService defines a service for application reflection.
 *
 * @generated from service cosmos.base.reflection.v2alpha1.ReflectionService
 */
export const ReflectionService = {
  typeName: 'cosmos.base.reflection.v2alpha1.ReflectionService',
  methods: {
    /**
     * GetAuthnDescriptor returns information on how to authenticate transactions in the application
     * NOTE: this RPC is still experimental and might be subject to breaking changes or removal in
     * future releases of the cosmos-sdk.
     *
     * @generated from rpc cosmos.base.reflection.v2alpha1.ReflectionService.GetAuthnDescriptor
     */
    getAuthnDescriptor: {
      name: 'GetAuthnDescriptor',
      I: GetAuthnDescriptorRequest,
      O: GetAuthnDescriptorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetChainDescriptor returns the description of the chain
     *
     * @generated from rpc cosmos.base.reflection.v2alpha1.ReflectionService.GetChainDescriptor
     */
    getChainDescriptor: {
      name: 'GetChainDescriptor',
      I: GetChainDescriptorRequest,
      O: GetChainDescriptorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetCodecDescriptor returns the descriptor of the codec of the application
     *
     * @generated from rpc cosmos.base.reflection.v2alpha1.ReflectionService.GetCodecDescriptor
     */
    getCodecDescriptor: {
      name: 'GetCodecDescriptor',
      I: GetCodecDescriptorRequest,
      O: GetCodecDescriptorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetConfigurationDescriptor returns the descriptor for the sdk.Config of the application
     *
     * @generated from rpc cosmos.base.reflection.v2alpha1.ReflectionService.GetConfigurationDescriptor
     */
    getConfigurationDescriptor: {
      name: 'GetConfigurationDescriptor',
      I: GetConfigurationDescriptorRequest,
      O: GetConfigurationDescriptorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetQueryServicesDescriptor returns the available gRPC queryable services of the application
     *
     * @generated from rpc cosmos.base.reflection.v2alpha1.ReflectionService.GetQueryServicesDescriptor
     */
    getQueryServicesDescriptor: {
      name: 'GetQueryServicesDescriptor',
      I: GetQueryServicesDescriptorRequest,
      O: GetQueryServicesDescriptorResponse,
      kind: MethodKind.Unary,
    },
    /**
     * GetTxDescriptor returns information on the used transaction object and available msgs that can be used
     *
     * @generated from rpc cosmos.base.reflection.v2alpha1.ReflectionService.GetTxDescriptor
     */
    getTxDescriptor: {
      name: 'GetTxDescriptor',
      I: GetTxDescriptorRequest,
      O: GetTxDescriptorResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
