// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file ethermint/evm/v1/tx.proto (package ethermint.evm.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  MsgEthereumTx,
  MsgEthereumTxResponse,
  MsgUpdateParams,
  MsgUpdateParamsResponse,
} from './tx_pb';
import { MethodKind } from '@bufbuild/protobuf';

/**
 * Msg defines the evm Msg service.
 *
 * @generated from service ethermint.evm.v1.Msg
 */
export const Msg = {
  typeName: 'ethermint.evm.v1.Msg',
  methods: {
    /**
     * EthereumTx defines a method submitting Ethereum transactions.
     *
     * @generated from rpc ethermint.evm.v1.Msg.EthereumTx
     */
    ethereumTx: {
      name: 'EthereumTx',
      I: MsgEthereumTx,
      O: MsgEthereumTxResponse,
      kind: MethodKind.Unary,
    },
    /**
     * UpdateParams defined a governance operation for updating the x/evm module
     * parameters. The authority is hard-coded to the Cosmos SDK x/gov module
     * account
     *
     * @generated from rpc ethermint.evm.v1.Msg.UpdateParams
     */
    updateParams: {
      name: 'UpdateParams',
      I: MsgUpdateParams,
      O: MsgUpdateParamsResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
