// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file haqq/coinomics/v1/query.proto (package haqq.coinomics.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  QueryMaxSupplyRequest,
  QueryMaxSupplyResponse,
  QueryParamsRequest,
  QueryParamsResponse,
  QueryRewardCoefficientRequest,
  QueryRewardCoefficientResponse,
} from './query_pb';
import { MethodKind } from '@bufbuild/protobuf';

/**
 * Query provides defines the gRPC querier service.
 *
 * @generated from service haqq.coinomics.v1.Query
 */
export const Query = {
  typeName: 'haqq.coinomics.v1.Query',
  methods: {
    /**
     * MaxSupply retrieves total coins of all eras and when mint ended.
     *
     * @generated from rpc haqq.coinomics.v1.Query.MaxSupply
     */
    maxSupply: {
      name: 'MaxSupply',
      I: QueryMaxSupplyRequest,
      O: QueryMaxSupplyResponse,
      kind: MethodKind.Unary,
    },
    /**
     * InflationRewardCoefficientRate APY rate for staking rewards
     *
     * @generated from rpc haqq.coinomics.v1.Query.RewardCoefficient
     */
    rewardCoefficient: {
      name: 'RewardCoefficient',
      I: QueryRewardCoefficientRequest,
      O: QueryRewardCoefficientResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Params retrieves coinomics moudle params.
     *
     * @generated from rpc haqq.coinomics.v1.Query.Params
     */
    params: {
      name: 'Params',
      I: QueryParamsRequest,
      O: QueryParamsResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
