// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file cosmos/gov/v1beta1/tx.proto (package cosmos.gov.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { MsgDeposit, MsgDepositResponse, MsgSubmitProposal, MsgSubmitProposalResponse, MsgVote, MsgVoteResponse, MsgVoteWeighted, MsgVoteWeightedResponse } from "./tx_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Msg defines the bank Msg service.
 *
 * @generated from service cosmos.gov.v1beta1.Msg
 */
export const Msg = {
  typeName: "cosmos.gov.v1beta1.Msg",
  methods: {
    /**
     * SubmitProposal defines a method to create new proposal given a content.
     *
     * @generated from rpc cosmos.gov.v1beta1.Msg.SubmitProposal
     */
    submitProposal: {
      name: "SubmitProposal",
      I: MsgSubmitProposal,
      O: MsgSubmitProposalResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Vote defines a method to add a vote on a specific proposal.
     *
     * @generated from rpc cosmos.gov.v1beta1.Msg.Vote
     */
    vote: {
      name: "Vote",
      I: MsgVote,
      O: MsgVoteResponse,
      kind: MethodKind.Unary,
    },
    /**
     * VoteWeighted defines a method to add a weighted vote on a specific proposal.
     *
     * Since: cosmos-sdk 0.43
     *
     * @generated from rpc cosmos.gov.v1beta1.Msg.VoteWeighted
     */
    voteWeighted: {
      name: "VoteWeighted",
      I: MsgVoteWeighted,
      O: MsgVoteWeightedResponse,
      kind: MethodKind.Unary,
    },
    /**
     * Deposit defines a method to add deposit on a specific proposal.
     *
     * @generated from rpc cosmos.gov.v1beta1.Msg.Deposit
     */
    deposit: {
      name: "Deposit",
      I: MsgDeposit,
      O: MsgDepositResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

