// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file evmos/epochs/v1/query.proto (package evmos.epochs.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryCurrentEpochRequest, QueryCurrentEpochResponse, QueryEpochsInfoRequest, QueryEpochsInfoResponse } from "./query_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service evmos.epochs.v1.Query
 */
export const Query = {
  typeName: "evmos.epochs.v1.Query",
  methods: {
    /**
     * EpochInfos provide running epochInfos
     *
     * @generated from rpc evmos.epochs.v1.Query.EpochInfos
     */
    epochInfos: {
      name: "EpochInfos",
      I: QueryEpochsInfoRequest,
      O: QueryEpochsInfoResponse,
      kind: MethodKind.Unary,
    },
    /**
     * CurrentEpoch provide current epoch of specified identifier
     *
     * @generated from rpc evmos.epochs.v1.Query.CurrentEpoch
     */
    currentEpoch: {
      name: "CurrentEpoch",
      I: QueryCurrentEpochRequest,
      O: QueryCurrentEpochResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

