// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file haqq/vesting/v1/query.proto (package haqq.vesting.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  QueryBalancesRequest,
  QueryBalancesResponse,
  QueryTotalLockedRequest,
  QueryTotalLockedResponse,
} from './query_pb';
import { MethodKind } from '@bufbuild/protobuf';

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service haqq.vesting.v1.Query
 */
export const Query = {
  typeName: 'haqq.vesting.v1.Query',
  methods: {
    /**
     * Balances retrieves the unvested, vested and locked tokens for a vesting
     * account
     *
     * @generated from rpc haqq.vesting.v1.Query.Balances
     */
    balances: {
      name: 'Balances',
      I: QueryBalancesRequest,
      O: QueryBalancesResponse,
      kind: MethodKind.Unary,
    },
    /**
     * TotalLocked retrieves the total summary of all unvested, vested and locked
     * tokens
     *
     * @generated from rpc haqq.vesting.v1.Query.TotalLocked
     */
    totalLocked: {
      name: 'TotalLocked',
      I: QueryTotalLockedRequest,
      O: QueryTotalLockedResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
