// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file cosmos/app/v1alpha1/query.proto (package cosmos.app.v1alpha1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryConfigRequest, QueryConfigResponse } from './query_pb';
import { MethodKind } from '@bufbuild/protobuf';

/**
 * Query is the app module query service.
 *
 * @generated from service cosmos.app.v1alpha1.Query
 */
export const Query = {
  typeName: 'cosmos.app.v1alpha1.Query',
  methods: {
    /**
     * Config returns the current app config.
     *
     * @generated from rpc cosmos.app.v1alpha1.Query.Config
     */
    config: {
      name: 'Config',
      I: QueryConfigRequest,
      O: QueryConfigResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;
