// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file tendermint/abci/types.proto (package tendermint.abci, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { RequestApplySnapshotChunk, RequestBeginBlock, RequestCheckTx, RequestCommit, RequestDeliverTx, RequestEcho, RequestEndBlock, RequestFlush, RequestInfo, RequestInitChain, RequestListSnapshots, RequestLoadSnapshotChunk, RequestOfferSnapshot, RequestPrepareProposal, RequestProcessProposal, RequestQuery, ResponseApplySnapshotChunk, ResponseBeginBlock, ResponseCheckTx, ResponseCommit, ResponseDeliverTx, ResponseEcho, ResponseEndBlock, ResponseFlush, ResponseInfo, ResponseInitChain, ResponseListSnapshots, ResponseLoadSnapshotChunk, ResponseOfferSnapshot, ResponsePrepareProposal, ResponseProcessProposal, ResponseQuery } from "./types_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service tendermint.abci.ABCIApplication
 */
export const ABCIApplication = {
  typeName: "tendermint.abci.ABCIApplication",
  methods: {
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.Echo
     */
    echo: {
      name: "Echo",
      I: RequestEcho,
      O: ResponseEcho,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.Flush
     */
    flush: {
      name: "Flush",
      I: RequestFlush,
      O: ResponseFlush,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.Info
     */
    info: {
      name: "Info",
      I: RequestInfo,
      O: ResponseInfo,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.DeliverTx
     */
    deliverTx: {
      name: "DeliverTx",
      I: RequestDeliverTx,
      O: ResponseDeliverTx,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.CheckTx
     */
    checkTx: {
      name: "CheckTx",
      I: RequestCheckTx,
      O: ResponseCheckTx,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.Query
     */
    query: {
      name: "Query",
      I: RequestQuery,
      O: ResponseQuery,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.Commit
     */
    commit: {
      name: "Commit",
      I: RequestCommit,
      O: ResponseCommit,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.InitChain
     */
    initChain: {
      name: "InitChain",
      I: RequestInitChain,
      O: ResponseInitChain,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.BeginBlock
     */
    beginBlock: {
      name: "BeginBlock",
      I: RequestBeginBlock,
      O: ResponseBeginBlock,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.EndBlock
     */
    endBlock: {
      name: "EndBlock",
      I: RequestEndBlock,
      O: ResponseEndBlock,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.ListSnapshots
     */
    listSnapshots: {
      name: "ListSnapshots",
      I: RequestListSnapshots,
      O: ResponseListSnapshots,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.OfferSnapshot
     */
    offerSnapshot: {
      name: "OfferSnapshot",
      I: RequestOfferSnapshot,
      O: ResponseOfferSnapshot,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.LoadSnapshotChunk
     */
    loadSnapshotChunk: {
      name: "LoadSnapshotChunk",
      I: RequestLoadSnapshotChunk,
      O: ResponseLoadSnapshotChunk,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.ApplySnapshotChunk
     */
    applySnapshotChunk: {
      name: "ApplySnapshotChunk",
      I: RequestApplySnapshotChunk,
      O: ResponseApplySnapshotChunk,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.PrepareProposal
     */
    prepareProposal: {
      name: "PrepareProposal",
      I: RequestPrepareProposal,
      O: ResponsePrepareProposal,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc tendermint.abci.ABCIApplication.ProcessProposal
     */
    processProposal: {
      name: "ProcessProposal",
      I: RequestProcessProposal,
      O: ResponseProcessProposal,
      kind: MethodKind.Unary,
    },
  }
} as const;

