// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file cosmos/evidence/v1beta1/query.proto (package cosmos.evidence.v1beta1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryAllEvidenceRequest, QueryAllEvidenceResponse, QueryEvidenceRequest, QueryEvidenceResponse } from "./query_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service cosmos.evidence.v1beta1.Query
 */
export const Query = {
  typeName: "cosmos.evidence.v1beta1.Query",
  methods: {
    /**
     * Evidence queries evidence based on evidence hash.
     *
     * @generated from rpc cosmos.evidence.v1beta1.Query.Evidence
     */
    evidence: {
      name: "Evidence",
      I: QueryEvidenceRequest,
      O: QueryEvidenceResponse,
      kind: MethodKind.Unary,
    },
    /**
     * AllEvidence queries all evidence.
     *
     * @generated from rpc cosmos.evidence.v1beta1.Query.AllEvidence
     */
    allEvidence: {
      name: "AllEvidence",
      I: QueryAllEvidenceRequest,
      O: QueryAllEvidenceResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

