name: Islamic-website Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_ISLAMIC_WEBSITE_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - prod
  workflow_dispatch:
jobs:
  Deploy-Preview:
    runs-on: frontend
    steps:
      - uses: actions/checkout@v2
      # - name: Install Vercel CLI
      #   run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build ./apps/islamic-website --token=${{ secrets.VERCEL_TOKEN }} --local-config vercel-next.json
      - name: Deploy to Vercel Action
        id: vercel-deploy
        uses: kioqq/deploy-to-vercel-action@v1.9.13
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_ISLAMIC_WEBSITE_PROJECT_ID }}
          GITHUB_DEPLOYMENT_ENV: IslamicCoin Website App Preview
          PRODUCTION: false
          PREBUILT: true
          CREATE_COMMENT: true
