name: Haqq-website Preview Deployment
# env:
#   VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
#   VERCEL_PROJECT_ID: ${{ secrets.VERCEL_HAQQ_WEBSITE_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - prod
  workflow_dispatch:
jobs:
  Deploy-Preview:
    runs-on: frontend
    steps:
      - uses: actions/checkout@v2
      # - name: Install Vercel CLI
      #   run: npm install --global vercel@latest
      # - uses: amondnet/vercel-action@v20
      #   with:
      #     vercel-token: ${{ secrets.VERCEL_TOKEN }}
      #     github-token: ${{ secrets.GITHUB_TOKEN }}
      #     vercel-args: '--local-config vercel-next.json'
      #     vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
      #     vercel-project-id: ${{ secrets.VERCEL_HAQQ_WEBSITE_PROJECT_ID}}
      #     # alias-domains: |
      #     #   haqq-website-{{BRANCH}}.vercel.app
      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_HAQQ_WEBSITE_PROJECT_ID }}
          GITHUB_DEPLOYMENT_ENV: Haqq Website Preview
          PRODUCTION: false
          ALIAS_DOMAINS: |
            haqq-web-{BRANCH}.vercel.app
            haqq-web-{BRANCH}.now.sh

# 'GITHUB_TOKEN', 'VERCEL_TOKEN', 'VERCEL_PROJECT_ID', 'VERCEL_ORG_ID', 'PRODUCTION', 'GITHUB_DEPLOYMENT', 'CREATE_COMMENT', 'DELETE_EXISTING_COMMENT', 'ATTACH_COMMIT_METADATA', 'DEPLOY_PR_FROM_FORK', 'PR_LABELS', 'ALIAS_DOMAINS', 'PR_PREVIEW_DOMAIN', 'VERCEL_SCOPE', 'GITHUB_DEPLOYMENT_ENV', 'TRIM_COMMIT_MESSAGE', 'BUILD_ENV', 'WORKING_DIRECTORY'
