name: Haqq-website Preview Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_HAQQ_WEBSITE_PROJECT_ID }}
on:
  push:
    branches-ignore:
      - prod
  workflow_dispatch:
jobs:
  Deploy-Preview:
    runs-on: frontend
    steps:
      - uses: actions/checkout@v2
      # - name: Install Vercel CLI
      #   run: npm install --global vercel@latest
      - uses: amondnet/vercel-action@v20 #deploy
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }} # Required
          github-token: ${{ secrets.GITHUB_TOKEN }} #Optional
          vercel-args: '--local-config vercel-next.json' #Optional
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}} #Required
          vercel-project-id: ${{ secrets.VERCEL_HAQQ_WEBSITE_PROJECT_ID}} #Required
