// Since: cosmos-sdk 0.47

// @generated by protoc-gen-connect-es v1.1.3 with parameter "target=ts"
// @generated from file cosmos/consensus/v1/query.proto (package cosmos.consensus.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { QueryParamsRequest, QueryParamsResponse } from "./query_pb.js";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * Query defines the gRPC querier service.
 *
 * @generated from service cosmos.consensus.v1.Query
 */
export const Query = {
  typeName: "cosmos.consensus.v1.Query",
  methods: {
    /**
     * Params queries the parameters of x/consensus_param module.
     *
     * @generated from rpc cosmos.consensus.v1.Query.Params
     */
    params: {
      name: "Params",
      I: QueryParamsRequest,
      O: QueryParamsResponse,
      kind: MethodKind.Unary,
    },
  }
} as const;

